#Swagger api configuration
springdoc:
  api-docs:
    path: /api-docs
  swagger-ui:
    path: /ProductPrice.html

#Database configuration
spring:
  h2:
    console:
      enabled: true
  datasource:
    url: jdbc:h2:mem:ecommercedb;DB_CLOSE_DELAY=-1;
    username: admin
    password:
  jpa:
    database-platform: org.hibernate.dialect.H2Dialect
    defer-datasource-initialization: true
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        show_sql: true
